---
body:
  - attributes:
      description: 在提交之前，请阅读并勾选统一下面的说明，否则该 issue 将被关闭。
      label: 前提说明
      options:
        - label: 本项目为自用项目，我理解提出的Issue不保证会有回复或修复
    id: ensure
    type: checkboxes
  - attributes:
      description: 请提供操作系统类型
      label: 操作系统
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
    type: dropdown
    validations:
      required: true
  - attributes:
      description: 请提供出现问题的操作系统版本，需要具体到小版本号，如果没有该 issues 将会被直接关闭
      label: 系统版本
    type: input
    validations:
      required: true
  - attributes:
      description: 请提供出现问题的软件版本，需要具体到小版本号，如果没有该 issues 将会被直接关闭
      label: 发生问题的软件版本
    type: input
    validations:
      required: true
  - attributes:
      description: 请提供错误的详细描述，如果没有该 issues 将会被直接关闭
      label: 描述
    type: textarea
    validations:
      required: true
  - attributes:
      description: 请提供重现错误的步骤，如果没有该 issues 将会被直接关闭
      label: 重现方式
    type: textarea
    validations:
      required: true
description: 提交Bug反馈
name: 错误反馈
title: '[Bug] '
