---
body:
  - attributes:
      description: 在提交之前，请阅读并勾选统一下面的说明，否则该 issue 将被关闭。
      label: 前提说明
      options:
        - label: 本项目为自用项目，我理解提出的Feature请求不保证会有回复或实现
    id: ensure
    type: checkboxes
  - attributes:
      description: 请提供操作系统类型
      label: 操作系统
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
    type: dropdown
    validations:
      required: true
  - attributes:
      description: 请提供所需功能的详细描述
      label: 描述
    type: textarea
    validations:
      required: true
description: 请求新功能或改进现有功能
name: 功能请求
title: '[Feature] '
